services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hewkawjang-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - FRONTEND_URL=${FRONTEND_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SUPABASE_PROJ_URL=${SUPABASE_PROJ_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - STRIPE_SK_API=${STRIPE_SK_API}
    restart: unless-stopped
    networks:
      - hewkawjang-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - EXPO_PUBLIC_BACKEND_URL=${EXPO_PUBLIC_BACKEND_URL}
        - EXPO_PUBLIC_SUPABASE_PROJ_URL=${EXPO_PUBLIC_SUPABASE_PROJ_URL}
        - EXPO_PUBLIC_SUPABASE_ANON_KEY=${EXPO_PUBLIC_SUPABASE_ANON_KEY}
    container_name: hewkawjang-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hewkawjang-network

networks:
  hewkawjang-network:
    driver: bridge
